name: "Self-test: Multistage docker build"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  selftest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1

      - name: Auth to GH registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./multistage-docker-build
        id: build
        with:
          dockerfile: examples/Dockerfile
          # repository: firehed/actions
          # repository: gcr.io/firehed/actions
          repository: ghcr.io/firehed/actions
          stages: env, configured
          target_test: testenv
          target_server: server

      - name: run tests
        run:
          docker run
            --rm
            -it ${{ steps.build.outputs.testenv-tag }}
            --
            echo "I'm a test!"
