name: "Self-test: Multistage docker build"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  selftest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./multistage-docker-build
        with:
          dockerfile: examples/Dockerfile
          # repository: firehed/actions
          repository: gcr.io/firehed/actions
          stages: env configured
          target_test: testenv
          target_server: server
